pimcore:
    assets:
        image:
            thumbnails:
                definitions:
                    product:
                        items:
                            -
                                method: scaleByWidth
                                arguments:
                                    width: 300
                                    forceResize: false
                        medias: {  }
                        name: product
                        description: 'product image'
                        group: ''
                        format: SOURCE
                        quality: 85
                        highResolution: 0.0
                        preserveColor: false
                        preserveMetaData: false
                        rasterizeSVG: false
                        downloadable: false
                        modificationDate: 1659878244
                        creationDate: 1659878181
                        preserveAnimation: false
